name: learn_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/icons/
    - assets/img/posts/large/
    - assets/img/posts/small/
    - assets/img/stories/
    - assets/img/background/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBook.otf
          weight: 200
        - asset: assets/fonts/AvenirLTProRoman.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProHeavy.otf
          weight: 700